### Créer un item
PUT http://localhost:80/items
Content-Type: application/json

{
    "name": "Exemple Item",
    "description": "Ceci est un exemple",
    "price": 100,
    "addProps": true
}

### Lire tous les items
GET http://localhost:80/items

### Lire un item
GET http://localhost:80/items/67a0a07190fdd80ccd1dd013

### Mettre à jour un item
PUT http://localhost:80/items/67a09a00c2bf2d430357cfc6
Content-Type: application/json

{
    "name": "Item mis à jour",
    "description": "Nouvelle description",
    "price": 150,
    "addProps": true
}

### Supprimer un item
DELETE http://localhost:80/items/67a09981bcae68475b85fbe4
